# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman
[tools]
rojo = "quenty/rojo@7.3.0-quenty-npm-canary.7"
wally = "6ixfalls/wally@0.0.0-nightly"
